import { useEffect, useMemo, useState } from 'react'
import {
  ArrowLeft, ArrowRight, BarChart3, BookOpen, Brain, Check, ChevronRight, CircleHelp,
  Flame, Home, Layers3, Menu, MoreHorizontal, PanelLeft, Play, Plus, RotateCcw,
  Settings, Sparkles, Target, Trophy, Volume2, X, Zap
} from 'lucide-react'
import { isSupabaseConfigured, loadCloudCards, saveCloudCards, supabase } from './lib/supabase'

type Card = { id: number; word: string; translation: string; example: string; level: string; interval: number; due: boolean; tag: string; phonetic: string }
type View = 'home' | 'learn' | 'library' | 'stats' | 'settings'

const seedCards: Card[] = [
  { id: 1, word: 'Serendipity', translation: 'счастливая случайность', example: 'Meeting her was a beautiful serendipity.', level: 'B2', interval: 1, due: true, tag: 'Feelings', phonetic: '/ˌserənˈdipitē/' },
  { id: 2, word: 'To linger', translation: 'задерживаться, медлить', example: 'The smell of coffee lingered in the room.', level: 'B1', interval: 2, due: true, tag: 'Actions', phonetic: '/ˈliŋɡər/' },
  { id: 3, word: 'Thorough', translation: 'тщательный, основательный', example: 'She did a thorough review of the report.', level: 'B2', interval: 4, due: true, tag: 'Quality', phonetic: '/ˈTHərō/' },
  { id: 4, word: 'To figure out', translation: 'разобраться, понять', example: 'I need a minute to figure out this problem.', level: 'B1', interval: 6, due: false, tag: 'Actions', phonetic: '/ˈfiɡyər aʊt/' },
  { id: 5, word: 'Insight', translation: 'понимание, проницательность', example: 'The book gave me a fresh insight into the topic.', level: 'B2', interval: 7, due: false, tag: 'Ideas', phonetic: '/ˈinsaɪt/' },
  { id: 6, word: 'Cozy', translation: 'уютный, удобный', example: 'It is a cozy little café near my house.', level: 'A2', interval: 10, due: false, tag: 'Places', phonetic: '/ˈkōzē/' },
]

const today = new Intl.DateTimeFormat('ru-RU', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())
const reviewLabels = ['Снова', 'Сложно', 'Хорошо', 'Легко']

function App() {
  const [view, setView] = useState<View>('home')
  const [cards, setCards] = useState<Card[]>(() => { try { return JSON.parse(localStorage.getItem('lingo-cards') || 'null') || seedCards } catch { return seedCards } })
  const [streak, setStreak] = useState(() => Number(localStorage.getItem('lingo-streak') || 7))
  const [isSidebarOpen, setSidebarOpen] = useState(false)
  const [isDark, setDark] = useState(false)
  const [dailyGoal, setDailyGoal] = useState(20)
  const [completedToday, setCompletedToday] = useState(() => Number(localStorage.getItem('lingo-today') || 8))
  const [showCreateSet, setShowCreateSet] = useState(false)
  const [customSetName, setCustomSetName] = useState(() => localStorage.getItem('lingo-custom-set') || '')
  const [cloudReady, setCloudReady] = useState(!isSupabaseConfigured)

  useEffect(() => { localStorage.setItem('lingo-cards', JSON.stringify(cards)); localStorage.setItem('lingo-streak', String(streak)); localStorage.setItem('lingo-today', String(completedToday)); if (customSetName) localStorage.setItem('lingo-custom-set', customSetName) }, [cards, streak, completedToday, customSetName])
  useEffect(() => { if (!supabase) return; loadCloudCards().then(cloudCards => { if (cloudCards.length) setCards(cloudCards); setCloudReady(true) }).catch(error => { console.warn('Supabase load failed:', error); setCloudReady(true) }) }, [])
  useEffect(() => { if (supabase && cloudReady) void saveCloudCards(cards) }, [cards, cloudReady])
  const dueCards = useMemo(() => cards.filter(c => c.due), [cards])

  const navigate = (next: View) => { setView(next); setSidebarOpen(false) }
  const markReviewed = (id: number, rating: number) => {
    setCards(prev => prev.map(c => c.id === id ? { ...c, due: false, interval: Math.max(1, c.interval * (rating + 1)) } : c))
    setCompletedToday(v => Math.min(dailyGoal, v + 1))
  }

  return <div className={isDark ? 'app dark' : 'app'}>
    <header className="topbar">
      <button className="mobile-menu icon-button" onClick={() => setSidebarOpen(v => !v)} aria-label="Открыть меню"><Menu size={21} /></button>
      <button className="brand" onClick={() => navigate('home')}><span className="brand-mark">M</span><span>Lingo</span></button>
      <div className="topbar-right"><div className="streak"><Flame size={17} fill="currentColor" /><b>{streak}</b><span>дней</span></div><button className="avatar">AS</button></div>
    </header>
    <div className="shell">
      <aside className={isSidebarOpen ? 'sidebar open' : 'sidebar'}>
        <nav>
          <SideItem icon={<Home size={19} />} label="Сегодня" active={view === 'home'} onClick={() => navigate('home')} />
          <SideItem icon={<Brain size={19} />} label="Учиться" badge={dueCards.length} active={view === 'learn'} onClick={() => navigate('learn')} />
          <SideItem icon={<Layers3 size={19} />} label="Мои наборы" active={view === 'library'} onClick={() => navigate('library')} />
          <SideItem icon={<BarChart3 size={19} />} label="Статистика" active={view === 'stats'} onClick={() => navigate('stats')} />
        </nav>
        <div className="sidebar-bottom"><div className="goal-mini"><div className="goal-mini-icon"><Target size={18} /></div><div><strong>Цель на сегодня</strong><span>{completedToday} из {dailyGoal} слов</span></div><ChevronRight size={16} /></div><SideItem icon={<Settings size={19} />} label="Настройки" active={view === 'settings'} onClick={() => navigate('settings')} /></div>
      </aside>
      <main className="main">{view === 'home' && <HomeView today={today} completed={completedToday} goal={dailyGoal} due={dueCards.length} navigate={navigate} streak={streak} />}{view === 'learn' && <LearnView cards={dueCards} onRate={markReviewed} onExit={() => navigate('home')} />}{view === 'library' && <LibraryView cards={cards} navigate={navigate} onCreate={() => setShowCreateSet(true)} customSetName={customSetName} />}{view === 'stats' && <StatsView cards={cards} completed={completedToday} streak={streak} />}{view === 'settings' && <SettingsView dark={isDark} setDark={setDark} goal={dailyGoal} setGoal={setDailyGoal} supabaseReady={Boolean(supabase)} />}</main>
    </div>
    <nav className="bottom-tabs"><SideItem icon={<Home size={20} />} label="Главная" active={view === 'home'} onClick={() => navigate('home')} /><SideItem icon={<Brain size={20} />} label="Учиться" badge={dueCards.length} active={view === 'learn'} onClick={() => navigate('learn')} /><SideItem icon={<Layers3 size={20} />} label="Наборы" active={view === 'library'} onClick={() => navigate('library')} /><SideItem icon={<BarChart3 size={20} />} label="Прогресс" active={view === 'stats'} onClick={() => navigate('stats')} /></nav>
    {showCreateSet && <CreateSetModal onClose={() => setShowCreateSet(false)} onCreate={(name, tag) => { setShowCreateSet(false); setCustomSetName(name); setCards(prev => [...prev, { id: Date.now(), word: 'First word', translation: 'Добавь перевод', example: 'Add your first example.', level: 'A1', interval: 1, due: true, tag: tag || 'My set', phonetic: '/first word/' }]) }} />}
  </div>
}

function SideItem({ icon, label, badge, active, onClick }: { icon: React.ReactNode; label: string; badge?: number; active?: boolean; onClick: () => void }) { return <button className={active ? 'side-item active' : 'side-item'} onClick={onClick}>{icon}<span>{label}</span>{badge ? <em>{badge}</em> : null}</button> }

function HomeView({ today, completed, goal, due, navigate, streak }: { today: string; completed: number; goal: number; due: number; navigate: (v: View) => void; streak: number }) {
  const progress = Math.round(completed / goal * 100)
  return <div className="content"><div className="welcome-row"><div><p className="eyebrow">{today}</p><h1>С возвращением, Samir<span className="accent-dot">.</span></h1><p className="muted">Маленький шаг сегодня — большая уверенность завтра.</p></div><div className="quick-streak"><span className="flame-circle"><Flame size={20} fill="currentColor" /></span><div><strong>{streak} дней</strong><span>твой текущий streak</span></div></div></div>
    <section className="hero-card"><div className="hero-copy"><div className="pill purple"><Sparkles size={14} /> Сессия готова</div><h2>Время освежить знания</h2><p>У тебя накопилось {due} {wordForm(due, 'слово', 'слова', 'слов')} для повторения. Это займёт около 5 минут.</p><button className="primary-button" onClick={() => navigate('learn')}><Play size={17} fill="currentColor" /> Начать повторение <ArrowRight size={17} /></button></div><div className="hero-art"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="art-card card-back"><span>meaning</span></div><div className="art-card card-front"><span>serendipity</span><small>/ˌserənˈdipitē/</small></div><div className="spark spark-one">✦</div><div className="spark spark-two">✦</div></div></section>
    <div className="section-heading"><div><h2>Твой прогресс</h2><p>Каждый день становится чуть легче</p></div><button className="text-button" onClick={() => navigate('stats')}>Подробнее <ArrowRight size={15} /></button></div>
    <div className="stats-grid"><div className="stat-card progress-card"><div className="stat-card-top"><span className="stat-icon green"><Target size={19} /></span><span className="stat-label">Цель на сегодня</span><MoreHorizontal size={18} className="more" /></div><div className="progress-number"><strong>{completed}</strong><span>/ {goal} слов</span></div><div className="progress-track"><i style={{ width: `${progress}%` }} /></div><span className="stat-foot">{goal - completed > 0 ? `Осталось ${goal - completed} ${wordForm(goal - completed, 'слово', 'слова', 'слов')}` : 'Цель выполнена'}</span></div><div className="stat-card"><div className="stat-card-top"><span className="stat-icon orange"><Flame size={19} /></span><span className="stat-label">Серия</span></div><div className="big-stat">{streak}<small> дней</small></div><span className="stat-foot positive">+2 дня к прошлой неделе</span></div><div className="stat-card"><div className="stat-card-top"><span className="stat-icon purple-bg"><Trophy size={19} /></span><span className="stat-label">Выучено всего</span></div><div className="big-stat">248</div><span className="stat-foot">+12 за эту неделю</span></div></div>
    <div className="section-heading deck-heading"><div><h2>Твои наборы</h2><p>Продолжай с того места, где остановился</p></div><button className="text-button" onClick={() => navigate('library')}>Все наборы <ArrowRight size={15} /></button></div><div className="deck-list"><DeckRow title="Everyday English" desc="Повседневные слова" count="124 слова" progress={68} color="blue" onClick={() => navigate('learn')} /><DeckRow title="Work & Business" desc="Для рабочих встреч" count="86 слов" progress={32} color="orange" onClick={() => navigate('learn')} /><DeckRow title="Travel essentials" desc="Английский в путешествиях" count="38 слов" progress={14} color="green" onClick={() => navigate('learn')} /></div>
  </div>
}

function DeckRow({ title, desc, count, progress, color, onClick }: { title: string; desc: string; count: string; progress: number; color: string; onClick: () => void }) { return <button className="deck-row" onClick={onClick}><div className={`deck-icon ${color}`}><BookOpen size={20} /></div><div className="deck-info"><strong>{title}</strong><span>{desc} · {count}</span></div><div className="deck-progress"><div><span>{progress}%</span><i><b style={{ width: `${progress}%` }} /></i></div></div><ChevronRight size={18} className="deck-arrow" /></button> }

function LearnView({ cards, onRate, onExit }: { cards: Card[]; onRate: (id: number, rating: number) => void; onExit: () => void }) {
  const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const card = cards[index]
  if (!card) return <div className="empty-state"><div className="empty-icon"><Check size={28} /></div><h1>На сегодня всё!</h1><p>Ты повторил все слова. Возвращайся завтра — новые карточки уже будут ждать.</p><button className="primary-button" onClick={onExit}><Home size={17} /> На главную</button></div>
  const rate = (value: number, _unused?: number) => { onRate(card.id, value); setRevealed(false); setIndex(v => v + 1) }
  return <div className="learn-page"><div className="learn-top"><button className="back-button" onClick={onExit}><X size={18} /> Завершить</button><div className="session-progress"><span>{index + 1} / {cards.length}</span><i><b style={{ width: `${(index / cards.length) * 100}%` }} /></i></div><button className="icon-button"><CircleHelp size={19} /></button></div><div className="learn-intro"><div><p className="eyebrow">Everyday English · повторение</p><h1>Вспомни перевод</h1></div><span className="session-score"><Zap size={15} fill="currentColor" /> +{index * 10} XP</span></div><div className={revealed ? 'flashcard revealed' : 'flashcard'} onClick={() => setRevealed(true)}><div className="card-top"><span className="pill soft">{card.tag}</span><span className="card-level">{card.level}</span></div><div className="flash-content"><h2>{card.word}</h2><span className="phonetic">{card.phonetic} <Volume2 size={16} /></span>{revealed ? <div className="answer"><div className="answer-divider" /><h3>{card.translation}</h3><p>“{card.example}”</p></div> : <span className="tap-hint">Нажми, чтобы увидеть перевод</span>}</div><div className="card-bottom"><RotateCcw size={16} /> {card.interval} {card.interval === 1 ? 'день' : 'дня'} назад</div></div><div className="review-area">{revealed ? <><p>Насколько легко вспомнилось?</p><div className="review-buttons">{reviewLabels.map((label, i) => <button key={label} className={`review-button review-${i}`} onClick={() => rate(i, i)}><span>{i + 1}</span>{label}<small>{i === 0 ? 'через 1 мин' : i === 1 ? 'через 1 день' : i === 2 ? 'через 4 дня' : 'через 10 дней'}</small></button>)}</div></> : <button className="primary-button reveal-button" onClick={() => setRevealed(true)}>Показать перевод <ArrowRight size={17} /></button>}</div></div>
}

function LibraryView({ cards, navigate, onCreate, customSetName }: { cards: Card[]; navigate: (v: View) => void; onCreate: () => void; customSetName: string }) {
  return <div className="content"><div className="page-title"><div><p className="eyebrow">Твоя коллекция</p><h1>Мои наборы</h1><p className="muted">Собирай слова вокруг того, что тебе интересно.</p></div><button className="primary-button" onClick={onCreate}><Plus size={18} /> Новый набор</button></div>{customSetName && <div className="custom-set-note"><span className="custom-set-dot" /><div><strong>{customSetName}</strong><span>Новый набор создан · 1 карточка ждёт заполнения</span></div><button className="text-button" onClick={() => navigate('learn')}>Открыть <ArrowRight size={15} /></button></div>}<div className="library-grid"><div className="library-card featured"><div className="library-cover blue-cover"><BookOpen size={28} /><span>EN</span></div><div className="library-card-body"><div className="card-meta"><span>124 слова</span><span>68% освоено</span></div><h3>Everyday English</h3><p>Самые нужные слова и фразы на каждый день.</p><div className="mini-progress"><i style={{ width: '68%' }} /></div><button className="outline-button" onClick={() => navigate('learn')}>Продолжить <ArrowRight size={15} /></button></div></div><div className="library-card"><div className="library-cover orange-cover"><BriefcaseIcon /><span>WORK</span></div><div className="library-card-body"><div className="card-meta"><span>86 слов</span><span>32% освоено</span></div><h3>Work & Business</h3><p>Уверенный английский для рабочих задач.</p><div className="mini-progress"><i style={{ width: '32%' }} /></div><button className="outline-button" onClick={() => navigate('learn')}>Продолжить <ArrowRight size={15} /></button></div></div><button className="library-card add-card" onClick={onCreate}><Plus size={25} /><strong>Добавить свой набор</strong><span>Создай набор и добавь первую карточку</span></button></div><div className="word-table"><div className="table-heading"><div><h2>Последние слова</h2><p>Всего {cards.length} карточек в коллекции</p></div><button className="text-button">Открыть словарь <ArrowRight size={15} /></button></div>{cards.slice(0, 4).map(card => <div className="word-row" key={card.id}><div className="word-letter">{card.word[0]}</div><div><strong>{card.word}</strong><span>{card.translation}</span></div><span className="word-tag">{card.tag}</span><span className="word-due">{card.due ? 'Повторить сегодня' : `Через ${card.interval} дн.`}</span><MoreHorizontal size={18} /></div>)}</div></div>
}

function CreateSetModal({ onClose, onCreate }: { onClose: () => void; onCreate: (name: string, tag: string) => void }) {
  const [name, setName] = useState('')
  const [tag, setTag] = useState('My set')
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e => e.stopPropagation()}><button className="modal-close icon-button" onClick={onClose} aria-label="Закрыть"><X size={20} /></button><div className="modal-icon"><Layers3 size={22} /></div><p className="eyebrow">Новая коллекция</p><h2>Создай свой набор</h2><p className="modal-copy">Начни с темы, которая тебе сейчас интересна.</p><label>Название набора<input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="Например, English for travel" /></label><label>Категория<input value={tag} onChange={e => setTag(e.target.value)} placeholder="Travel" /></label><button className="primary-button modal-submit" disabled={!name.trim()} onClick={() => onCreate(name, tag)}>Создать набор <ArrowRight size={17} /></button></div></div>
}
function BriefcaseIcon() { return <Layers3 size={28} /> }
function StatsView({ cards, completed, streak }: { cards: Card[]; completed: number; streak: number }) { return <div className="content"><div className="page-title"><div><p className="eyebrow">Не останавливайся</p><h1>Твоя статистика</h1><p className="muted">Прогресс складывается из маленьких привычек.</p></div><div className="period-switch"><button>Неделя</button><button className="selected">Месяц</button><button>Всё время</button></div></div><div className="stats-large-grid"><div className="stat-card large-stat"><span className="stat-label">Слов выучено</span><strong>248</strong><span className="positive">+18% к прошлому месяцу</span><div className="chart"><i style={{ height: '28%' }} /><i style={{ height: '44%' }} /><i style={{ height: '39%' }} /><i style={{ height: '60%' }} /><i style={{ height: '53%' }} /><i style={{ height: '78%' }} /><i style={{ height: '91%' }} /><i style={{ height: '66%' }} /><i style={{ height: '82%' }} /><i style={{ height: '100%' }} /></div><div className="chart-labels"><span>1 сен</span><span>15 сен</span><span>30 сен</span></div></div><div className="stat-card large-stat"><span className="stat-label">Точность ответов</span><strong>84<small>%</small></strong><span className="positive">+6% за месяц</span><div className="accuracy-ring"><div><strong>84%</strong><span>точность</span></div></div></div><div className="stat-card large-stat"><span className="stat-label">Текущая серия</span><strong>{streak}<small> дней</small></strong><span className="stat-foot">Рекорд: 14 дней</span><div className="week-dots">{['П','В','С','Ч','П','С','В'].map((d, i) => <div key={d + i}><span className={i < 5 ? 'done' : i === 5 ? 'today' : ''}>{i < 5 ? <Check size={13} /> : ''}</span><small>{d}</small></div>)}</div></div></div><div className="insight"><div className="insight-icon"><Sparkles size={20} /></div><div><strong>Хороший ритм!</strong><p>Ты отвечаешь правильно в 84% случаев. Попробуй заниматься по 10 минут в день — так слова перейдут в долгую память быстрее.</p></div></div><div className="stats-note"><BarChart3 size={18} /><span>За сегодня повторено <strong>{completed} слов</strong>. В коллекции сейчас {cards.length} активных карточек.</span></div></div> }
function SettingsView({ dark, setDark, goal, setGoal, supabaseReady }: { dark: boolean; setDark: (v: boolean) => void; goal: number; setGoal: (v: number) => void; supabaseReady: boolean }) { return <div className="content narrow"><div className="page-title"><div><p className="eyebrow">Под себя</p><h1>Настройки</h1><p className="muted">Настрой Lingo под свой ритм.</p></div></div><div className="settings-section"><h2>Обучение</h2><div className="setting-row"><div><strong>Цель на день</strong><span>Сколько новых повторений планировать</span></div><div className="goal-options">{[10, 20, 30].map(n => <button key={n} className={goal === n ? 'chosen' : ''} onClick={() => setGoal(n)}>{n}</button>)}</div></div><div className="setting-row"><div><strong>Синхронизация</strong><span>{supabaseReady ? 'Supabase подключён' : 'Работает локальное сохранение'}</span></div><span className={supabaseReady ? 'status connected' : 'status'}>{supabaseReady ? 'Подключено' : 'Локально'}</span></div></div><div className="settings-section"><h2>Внешний вид</h2><div className="setting-row"><div><strong>Тёмная тема</strong><span>Комфортный режим для занятий вечером</span></div><button className={dark ? 'toggle on' : 'toggle'} onClick={() => setDark(!dark)}><i /></button></div></div><div className="settings-section"><h2>Аккаунт</h2><div className="profile-line"><div className="avatar large">AS</div><div><strong>Samir</strong><span>samir@example.com</span></div><button className="outline-button small">Изменить профиль</button></div></div></div> }
function wordForm(n: number, one: string, few: string, many: string) { const m = n % 100; return m >= 11 && m <= 19 ? many : n % 10 === 1 ? one : n % 10 >= 2 && n % 10 <= 4 ? few : many }

export default App
