create table if not exists public.decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text not null default '',
  color text not null default 'blue',
  created_at timestamptz not null default now()
);

create table if not exists public.review_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id bigint not null,
  rating integer not null check (rating between 0 and 3),
  interval integer not null default 1,
  created_at timestamptz not null default now()
);

alter table public.decks enable row level security;
alter table public.review_logs enable row level security;

drop policy if exists "Users can read their own decks" on public.decks;
create policy "Users can read their own decks" on public.decks for select using (auth.uid() = user_id);
drop policy if exists "Users can insert their own decks" on public.decks;
create policy "Users can insert their own decks" on public.decks for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update their own decks" on public.decks;
create policy "Users can update their own decks" on public.decks for update using (auth.uid() = user_id);

drop policy if exists "Users can read their own reviews" on public.review_logs;
create policy "Users can read their own reviews" on public.review_logs for select using (auth.uid() = user_id);
drop policy if exists "Users can insert their own reviews" on public.review_logs;
create policy "Users can insert their own reviews" on public.review_logs for insert with check (auth.uid() = user_id);
